// Generated by cmd/gen/main.go. DO NOT EDIT.
package wavetable

var Breakpoints = []float64{0.000454, 0.000907, 0.001814, 0.003628, 0.007256, 0.014512, 0.029025, 0.058050, 0.116100}

var Tables = map[string][]float64{"sine": Sine[:], "saw": Saw[:], "square": Square[:], "triangle": Triangle[:]}